# Generated by Django 4.2.5 on 2023-09-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NGram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, unique=True)),
                ("n", models.PositiveIntegerField(db_index=True)),
                ("frequency", models.PositiveIntegerField(db_index=True)),
                ("pct", models.FloatField(db_index=True)),
                ("adj_pct", models.FloatField(db_index=True)),
                ("song_pct", models.FloatField(db_index=True)),
                ("title_pct", models.FloatField(db_index=True)),
                ("mscore", models.FloatField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "NGram",
                "verbose_name_plural": "NGrams",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor", models.CharField(max_length=200)),
                ("alt1", models.CharField(blank=True, max_length=200, null=True)),
                ("alt2", models.CharField(blank=True, max_length=200, null=True)),
                ("voter_uid", models.SlugField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("alt1", "Alt1"),
                            ("alt2", "Alt2"),
                            ("both", "Both"),
                            ("neither", "Neither"),
                            ("flagged", "Flagged"),
                            ("good", "Good"),
                            ("bad", "Bad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "unique_together": {("voter_uid", "created")},
            },
        ),
        migrations.CreateModel(
            name="Rhyme",
            fields=[
                ("uid", models.SlugField(primary_key=True, serialize=False)),
                ("frequency", models.PositiveIntegerField(db_index=True)),
                ("song_ct", models.PositiveIntegerField(db_index=True)),
                ("score", models.FloatField(db_index=True)),
                ("uscore", models.FloatField(db_index=True)),
                ("source", models.SlugField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "from_ngram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rhymed_from",
                        to="rhymes.ngram",
                    ),
                ),
                (
                    "to_ngram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rhymed_to",
                        to="rhymes.ngram",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_ngram", "to_ngram")},
            },
        ),
        migrations.AddField(
            model_name="ngram",
            name="rhymes",
            field=models.ManyToManyField(through="rhymes.Rhyme", to="rhymes.ngram"),
        ),
        migrations.CreateModel(
            name="Cache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="data/cache"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "unique_together": {("key", "version")},
            },
        ),
    ]
