# Generated by Django 4.2.5 on 2023-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rhymes", "0002_rhyme_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor", models.CharField(max_length=200)),
                ("alt1", models.CharField(blank=True, max_length=200, null=True)),
                ("alt2", models.CharField(blank=True, max_length=200, null=True)),
                ("voter_uid", models.SlugField()),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("alt1", "Alt1"),
                            ("alt2", "Alt2"),
                            ("both", "Both"),
                            ("neither", "Neither"),
                            ("flagged", "Flagged"),
                            ("good", "Good"),
                            ("bad", "Bad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "unique_together": {("voter_uid", "created")},
            },
        ),
    ]
