# Generated by Django 4.2.5 on 2023-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rhymes", "0003_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhyme",
            name="source",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
