# Generated by Django 4.0.4 on 2022-05-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('n', models.PositiveIntegerField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'NGram',
                'verbose_name_plural': 'NGrams',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('lyrics_raw', models.TextField(blank=True, null=True)),
                ('lyrics_ipa', models.TextField(blank=True, null=True)),
                ('rhymes_raw', models.TextField(blank=True, null=True)),
                ('spotify_id', models.SlugField(blank=True, null=True, unique=True)),
                ('jaxsta_id', models.SlugField(blank=True, null=True)),
                ('youtube_id', models.SlugField(blank=True, null=True, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='data/audio')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='songs', to='api.artist')),
                ('ngrams', models.ManyToManyField(blank=True, related_name='songs', to='api.ngram')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('song', 'Song'), ('snippet', 'Snippet')], default='song', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_texts', to='api.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='songs', to='api.tag'),
        ),
        migrations.AddField(
            model_name='song',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='songs', to='api.writer'),
        ),
        migrations.CreateModel(
            name='Rhyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('from_ngram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhymed_from', to='api.ngram')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhymes', to='api.song')),
                ('to_ngram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhymed_to', to='api.ngram')),
            ],
            options={
                'unique_together': {('from_ngram', 'to_ngram', 'song')},
            },
        ),
        migrations.AddField(
            model_name='ngram',
            name='rhymes',
            field=models.ManyToManyField(through='api.Rhyme', to='api.ngram'),
        ),
    ]
