# Generated by Django 4.0.4 on 2022-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='ipa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngram',
            name='phones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ngram',
            name='stresses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
