# Generated by Django 4.0.4 on 2022-05-30 04:05

import re
from django.db import migrations

def update_ngrams(apps, schema_editor):
    NGram = apps.get_model('api', 'NGram')
    for ngram in NGram.objects.all():
        if ngram.phones:
            ngram.phones = re.sub(r'[A-Z]+\b', '', ngram.phones)
            ngram.phones = re.sub(r'\s+', ' ', ngram.phones)
            ngram.phones = ngram.phones.strip()
            ngram.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ngram_ipa_ngram_phones_ngram_stresses'),
    ]

    operations = [
        migrations.RunPython(update_ngrams)
    ]
