# Generated by Django 4.0.4 on 2022-06-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220530_0005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('category', 'value')},
        ),
    ]
