# Generated by Django 4.0.4 on 2022-06-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
