# Generated by Django 4.0.4 on 2022-06-04 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_song_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='formants',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4), blank=True, null=True, size=None),
        ),
    ]
