# Generated by Django 4.0.5 on 2022-06-09 18:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_writer_alt_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongNGram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('ngram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ngram')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='ngrams_new',
            field=models.ManyToManyField(blank=True, through='api.SongNGram', to='api.ngram'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='alt_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, unique=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='songngram',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song'),
        ),
        migrations.AlterUniqueTogether(
            name='songngram',
            unique_together={('ngram', 'song')},
        ),
    ]
