# Generated by Django 4.0.5 on 2022-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_songngram_song_ngrams_new_alter_writer_alt_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='ngrams',
        ),
    ]
