# Generated by Django 4.0.5 on 2022-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_song_ngrams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='ngrams_new',
            new_name='ngrams',
        ),
    ]
