# Generated by Django 4.0.5 on 2022-06-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_ngrams_new_song_ngrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songngram',
            name='ngram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_ngrams', to='api.ngram'),
        ),
        migrations.AlterField(
            model_name='songngram',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_ngrams', to='api.song'),
        ),
    ]
