# Generated by Django 4.0.5 on 2022-06-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_songngram_ngram_alter_songngram_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ngrams',
            field=models.ManyToManyField(blank=True, related_name='songs', through='api.SongNGram', to='api.ngram'),
        ),
    ]
