# Generated by Django 4.0.5 on 2022-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_song_ngrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
