# Generated by Django 4.0.5 on 2022-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ngram_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngram',
            name='score',
        ),
        migrations.AddField(
            model_name='ngram',
            name='adj_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngram',
            name='pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
