# Generated by Django 4.0.5 on 2022-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_ngram_score_ngram_adj_pct_ngram_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngram',
            name='adj_pct',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ngram',
            name='pct',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ngram',
            name='phones',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songngram',
            name='count',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
