# Generated by Django 4.0.5 on 2022-06-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_ngram_adj_pct_alter_ngram_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhyme',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='rhyme',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rhymes', to='api.song'),
        ),
    ]
