# Generated by Django 4.0.5 on 2022-06-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rhyme_level_alter_rhyme_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngram',
            name='formants',
        ),
        migrations.RemoveField(
            model_name='ngram',
            name='stresses',
        ),
        migrations.AddField(
            model_name='ngram',
            name='mscore',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
