# Generated by Django 4.0.5 on 2022-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_ngram_formants_remove_ngram_stresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngram',
            name='mscore',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
