# Generated by Django 4.0.5 on 2022-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ngram_mscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngram',
            name='mscore',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
