# Generated by Django 4.0.5 on 2022-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_metadata_cache_data_cache_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='cache',
            unique_together={('key', 'version')},
        ),
    ]
