# Generated by Django 4.0.5 on 2022-06-23 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_cache_key_alter_cache_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngram',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, db_index=True, null=True, size=None),
        ),
    ]
