# Generated by Django 4.0.5 on 2022-06-29 01:51

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0024_alter_ngram_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='stresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attachment_type', models.SlugField()),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.attachment_upload_path)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'attachment_type', 'file')},
            },
        ),
    ]
