# Generated by Django 4.0.5 on 2022-06-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
