# Generated by Django 4.0.5 on 2022-06-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_song_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics_ipa',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics_raw',
        ),
    ]
