# Generated by Django 4.0.5 on 2022-07-07 12:31

import api.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_song_lyrics_ipa_remove_song_lyrics_raw'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attachment',
            managers=[
                ('objects', api.managers.AttachmentManager()),
            ],
        ),
        migrations.AddField(
            model_name='ngram',
            name='title_pct',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
