# Generated by Django 4.0.5 on 2022-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_attachment_managers_ngram_title_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='song_pct',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
