# Generated by Django 4.0.5 on 2022-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ngram_song_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ngram',
            name='song_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
